import { Client } from './types';

export const TOMORROW_CLIENTS: Client[] = [
  {
    id: 'client-1',
    clientName: 'Eileen Tan-Khoo',
    callTime: '08:30 AM',
    lastContact: '11 days ago',
    callReason: 'Scheduled quarterly asset allocation review following her family trust cash distribution.',
    statedPriority: 'Protect capital for my children’s overseas education while keeping cash yields above inflation.',
    talkingPoints: [
      {
        id: 'tp-1-1',
        point: 'Your SGD fixed deposit tranche of 1.2 million matured yesterday into your call account.',
        reason: 'You need this deployed quickly into short-tenor paper so idle cash does not drag your quarterly yield.',
        source: 'Deposit maturity alert, 06 Sep',
      },
      {
        id: 'tp-1-2',
        point: 'The regional sovereign debt allocation dropped below your 25% minimum target after last week’s rally.',
        reason: 'Rebalancing now locks in equity gains and restores the defensive buffer you requested for the trust.',
        source: 'Mandate drift report, 04 Sep',
      },
      {
        id: 'tp-1-3',
        point: 'Your secondary family office entity completed its statutory tax residency certification.',
        reason: 'This unlocks the lower withholding rate on your cross-border dividend distributions starting this month.',
        source: 'Fiduciary services update, 01 Sep',
      },
    ],
  },
  {
    id: 'client-2',
    clientName: 'Bernard Seah',
    callTime: '09:15 AM',
    lastContact: '18 days ago',
    callReason: 'Follow-up on credit facility drawdown requested for a regional logistics acquisition.',
    statedPriority: 'Maintain absolute borrowing flexibility without pledging operational operating company stock.',
    talkingPoints: [
      {
        id: 'tp-2-1',
        point: 'The collateral haircut on your investment-grade bond portfolio was revised favorably from 30% to 22%.',
        reason: 'This increases your available Lombard credit line by 650,000 SGD without requiring additional securities.',
        source: 'Risk committee bulletin, 05 Sep',
      },
      {
        id: 'tp-2-2',
        point: 'Three-month SIBOR benchmark rates softened by 14 basis points over the past fortnight.',
        reason: 'Your floating-rate drawdown will price cheaper than your initial financial model assumed.',
        source: 'Treasury desk brief, 03 Sep',
      },
      {
        id: 'tp-2-3',
        point: 'Your nominee holding agreement for the Jurong warehouse vehicle is ready for execution.',
        reason: 'Signing this week prevents delays in closing the transaction ahead of the quarter-end deadline.',
        source: 'Legal advisory note, 28 Aug',
      },
    ],
  },
  {
    id: 'client-3',
    clientName: 'Marcus Lim',
    callTime: '10:00 AM',
    lastContact: '5 days ago',
    callReason: 'Pre-meeting prep for restructuring his discretionary technology mandate.',
    statedPriority: 'Reduce single-sector volatility after outsized tech gains without triggering early redemption penalties.',
    talkingPoints: [
      {
        id: 'tp-3-1',
        point: 'The discretionary equity portfolio triggered a trim threshold after crossing 32% net gain year-to-date.',
        reason: 'Harvesting partial gains now aligns with your agreement to cap semiconductor sector exposure at 15%.',
        source: 'Portfolio review, 05 Sep',
      },
      {
        id: 'tp-3-2',
        point: 'A structured note linked to ASEAN infrastructure utilities opened for your private banking tier.',
        reason: 'It offers the 6.2% annual coupon target you wanted while providing 90% capital downside protection.',
        source: 'Structured products desk, 02 Sep',
      },
      {
        id: 'tp-3-3',
        point: 'Your discretionary mandate fee schedule was credited with the loyalty rebate from the prior fiscal year.',
        reason: 'Your effective management fee for the upcoming quarter will be 18 basis points lower than standard.',
        source: 'Operations fee reconciliation, 30 Aug',
      },
    ],
  },
  {
    id: 'client-4',
    clientName: 'Dr. Cheryl Chew',
    callTime: '10:45 AM',
    lastContact: '3 weeks ago',
    callReason: 'Check-in on currency exposure following her clinical group’s medical equipment purchase from Japan.',
    statedPriority: 'Hedge Japanese Yen liability before payment due date while preserving Singapore Dollar cash reserves.',
    talkingPoints: [
      {
        id: 'tp-4-1',
        point: 'The JPY/SGD exchange rate moved back into your pre-set hedging strike window of 112.50.',
        reason: 'Booking your forward contract today locks in the equipment budget well below your approved board cap.',
        source: 'FX advisory alert, 06 Sep',
      },
      {
        id: 'tp-4-2',
        point: 'Your medical practice corporate treasury account received 420,000 SGD in patient insurance reimbursements.',
        reason: 'You have sufficient internal cash to settle the forward without tapping your working capital overdraft.',
        source: 'Account transaction summary, 04 Sep',
      },
      {
        id: 'tp-4-3',
        point: 'Your private banking dual-currency placement matured with full principal return in SGD.',
        reason: 'This frees up 300,000 SGD that can now be placed into the higher-yielding institutional money market fund.',
        source: 'Structured deposit statement, 31 Aug',
      },
    ],
  },
  {
    id: 'client-5',
    clientName: 'Winston Ong',
    callTime: '11:30 AM',
    lastContact: '26 days ago',
    callReason: 'Semi-annual governance check on multi-currency liquidity reserves.',
    statedPriority: 'Keep 4 million SGD in highly liquid instruments ready for sudden private equity capital calls.',
    talkingPoints: [
      {
        id: 'tp-5-1',
        point: 'The private debt fund you committed to issued a preliminary capital call notice for late next month.',
        reason: 'You need to earmark 850,000 SGD from your maturing certificates to fund the first project deployment.',
        source: 'Fund administrator letter, 03 Sep',
      },
      {
        id: 'tp-5-2',
        point: 'Singapore 6-month Treasury Bill yields printed higher at 3.65% on the latest auction cutoff.',
        reason: 'Rolling your liquid cash into these bills beats your current sweep rate by 45 basis points with zero credit risk.',
        source: 'Fixed income morning note, 02 Sep',
      },
      {
        id: 'tp-5-3',
        point: 'Your primary signatory mandate was successfully updated to include your newly appointed family office COO.',
        reason: 'Your office can now verify trade confirmations even when you are traveling in London next week.',
        source: 'Client documentation desk, 27 Aug',
      },
    ],
  },
  {
    id: 'client-6',
    clientName: 'Haryanto Wijaya',
    callTime: '01:15 PM',
    lastContact: '14 days ago',
    callReason: 'Cross-border estate succession planning review and offshore holding entity setup.',
    statedPriority: 'Ensure smooth intergenerational transfer of Singapore real estate assets to my two grandchildren.',
    talkingPoints: [
      {
        id: 'tp-6-1',
        point: 'The draft trust deed for the Singapore Variable Capital Company structure was delivered by external counsel.',
        reason: 'Reviewing the appointment of the protector clause now ensures your control parameters remain intact.',
        source: 'Trust advisory submission, 05 Sep',
      },
      {
        id: 'tp-6-2',
        point: 'Your commercial real estate syndicate unit in Tanjong Pagar declared its interim dividend payout of 4.8%.',
        reason: 'The 180,000 SGD cash distribution will be credited directly to your succession trust account this Friday.',
        source: 'Custodian distribution notice, 01 Sep',
      },
      {
        id: 'tp-6-3',
        point: 'The bank’s philanthropic foundation partner submitted the matching grant proposal for your medical bursary.',
        reason: 'Approving the charter by mid-month doubles the endowment impact for the upcoming academic year.',
        source: 'Philanthropy advisory desk, 25 Aug',
      },
    ],
  },
  {
    id: 'client-7',
    clientName: 'Grace Koh-Phua',
    callTime: '02:00 PM',
    lastContact: '8 days ago',
    callReason: 'Review of ESG-screened sustainable fixed income portfolio post-coupon cycle.',
    statedPriority: '100% compliant green-bond portfolio yielding at least 4.2% without exposure to fossil fuels.',
    talkingPoints: [
      {
        id: 'tp-7-1',
        point: 'An ASEAN supranational green development bond opened for subscription with an indicated 4.35% coupon.',
        reason: 'It matches your strict Article 9 sustainability criteria while replacing your lower-yielding corporate paper.',
        source: 'Green bond syndication brief, 05 Sep',
      },
      {
        id: 'tp-7-2',
        point: 'Your quarterly sustainability impact report confirmed a 38% portfolio carbon intensity reduction over last year.',
        reason: 'You can present this exact verified metric at your family foundation’s annual general meeting this Thursday.',
        source: 'Impact analytics report, 02 Sep',
      },
      {
        id: 'tp-7-3',
        point: 'One municipal water utility bond in your portfolio was upgraded from BBB+ to A- by the ratings agency.',
        reason: 'The credit enhancement eliminates the minor covenant concern you noted during our previous call.',
        source: 'Credit research bulletin, 29 Aug',
      },
    ],
  },
  {
    id: 'client-8',
    clientName: 'Suresh Ramanathan',
    callTime: '02:45 PM',
    lastContact: '32 days ago',
    callReason: 'Annual comprehensive wealth review and discussion of alternative investment access.',
    statedPriority: 'Grow private market allocation to 20% of total wealth while keeping leverage strictly under 15%.',
    talkingPoints: [
      {
        id: 'tp-8-1',
        point: 'Your private equity co-investment in Southeast Asian digital infrastructure closed with full allocation.',
        reason: 'This completes the planned 1.5 million USD second tranche without diluting your governance observer rights.',
        source: 'Private markets closing notice, 04 Sep',
      },
      {
        id: 'tp-8-2',
        point: 'Your overall portfolio leverage ratio dipped to 9.8% following the appreciation of your equity holdings.',
        reason: 'You have ample headroom below your 15% self-imposed limit to support any opportunistic co-investments.',
        source: 'Margin monitoring system, 01 Sep',
      },
      {
        id: 'tp-8-3',
        point: 'Your accredited investor certification renewal package was pre-filled and requires your single digital signature.',
        reason: 'Submitting it before next Monday prevents any administrative hold on your private placement subscriptions.',
        source: 'Compliance onboarding desk, 26 Aug',
      },
    ],
  },
  {
    id: 'client-9',
    clientName: 'Victor Chen',
    callTime: '03:30 PM',
    lastContact: '16 days ago',
    callReason: 'Strategy call on yield enhancement across his Singapore and Hong Kong custody accounts.',
    statedPriority: 'Optimize cash drag across multi-currency business proceeds while awaiting maritime shipping contract closings.',
    talkingPoints: [
      {
        id: 'tp-9-1',
        point: 'US Dollar liquidity yields on short-duration institutional treasury repos rebounded to 5.15%.',
        reason: 'Parking your 2.4 million USD idle escrow balance here earns an extra 11,000 USD monthly with daily liquidity.',
        source: 'Money market desk update, 06 Sep',
      },
      {
        id: 'tp-9-2',
        point: 'The cross-border custody netting facility between Singapore and Hong Kong has been fully approved.',
        reason: 'You no longer need to wire collateral between jurisdictions to meet daily trading buffer requirements.',
        source: 'Custody operations bulletin, 02 Sep',
      },
      {
        id: 'tp-9-3',
        point: 'A maritime green transition credit fund you evaluated posted its audited semi-annual net IRR of 9.4%.',
        reason: 'The performance validates the business model you were interested in backing as an anchor limited partner.',
        source: 'Fund manager disclosure, 28 Aug',
      },
    ],
  },
  {
    id: 'client-10',
    clientName: 'Dora Ng',
    callTime: '04:15 PM',
    lastContact: '9 days ago',
    callReason: 'Review of retirement annuity structure and sovereign inflation-linked securities.',
    statedPriority: 'Predictable quarterly income streams that require minimal active management from my side.',
    talkingPoints: [
      {
        id: 'tp-10-1',
        point: 'Your semi-annual annuity payout of 65,000 SGD was credited into your designated lifestyle current account.',
        reason: 'This covers your family travel expenditures for the remaining calendar year without liquidating core investments.',
        source: 'Cash management advice, 05 Sep',
      },
      {
        id: 'tp-10-2',
        point: 'The inflation-protected sovereign bond ladder we built achieved its targeted 4.6% real coupon yield.',
        reason: 'Your purchasing power remains insulated against local medical and food inflation increases.',
        source: 'Fixed income quarterly audit, 03 Sep',
      },
      {
        id: 'tp-10-3',
        point: 'The standby power of attorney document for medical incapacity was ratified by your appointed lawyer.',
        reason: 'The bank now has the official legal counterpart on file, ensuring seamless continuity as you requested.',
        source: 'Estate governance records, 24 Aug',
      },
    ],
  },
  {
    id: 'client-11',
    clientName: 'Benedict Teo',
    callTime: '05:00 PM',
    lastContact: '21 days ago',
    callReason: 'Discussion on pre-IPO private placement liquidity options and debt financing.',
    statedPriority: 'Monetize a portion of private tech shares ahead of listing without forfeiting founder board control.',
    talkingPoints: [
      {
        id: 'tp-11-1',
        point: 'A secondary market institutional buyer submitted a formal bid for up to 5% of your series-C private shares.',
        reason: 'This provides the 3 million SGD liquidity window you wanted without needing an early company IPO filing.',
        source: 'Direct investments desk, 04 Sep',
      },
      {
        id: 'tp-11-2',
        point: 'Our private bank structured lending team approved a non-recourse founder credit line against vested stock.',
        reason: 'You can access immediate cash for your new venture while retaining 100% of your voting rights.',
        source: 'Structured credit term sheet, 02 Sep',
      },
      {
        id: 'tp-11-3',
        point: 'The Singapore exchange announced updated dual-class share listing guidelines favoring enterprise software firms.',
        reason: 'Your advisory consortium can proceed with the preferred Singapore domestic listing roadmap.',
        source: 'Capital markets advisory alert, 29 Aug',
      },
    ],
  },
  {
    id: 'client-12',
    clientName: 'Aylwin Chia',
    callTime: '05:45 PM',
    lastContact: '4 days ago',
    callReason: 'Urgent mandate re-alignment following a sudden corporate dividend influx.',
    statedPriority: 'Immediate deployment of 1.8 million SGD windfall into defensive, high-dividend defensive equities.',
    talkingPoints: [
      {
        id: 'tp-12-1',
        point: 'The Singapore blue-chip banking and telecom dividend basket currently offers an average 5.8% dividend yield.',
        reason: 'Deploying the windfall here immediately fulfills your mandate for defensive, recurring quarterly cash flow.',
        source: 'Equity research recommendations, 06 Sep',
      },
      {
        id: 'tp-12-2',
        point: 'Your dividend reinvestment plan was successfully activated across all nine existing local equity holdings.',
        reason: 'Future distributions will automatically compound into new shares without incurring odd-lot brokerage fees.',
        source: 'Operations execution receipt, 04 Sep',
      },
      {
        id: 'tp-12-3',
        point: 'A capital gains tax clearance letter for your Australian property sale was received by our escrow team.',
        reason: 'The remaining 450,000 AUD held in reserve has been released and is ready for currency conversion.',
        source: 'Tax & legal clearance notice, 01 Sep',
      },
    ],
  },
];
